package za.skadush.codegen.gradle.annotations

import kotlin.reflect.KClass

/**
 * Default field configuration applied to **every** output class generated by this spec class.
 *
 * Carries params meaningful for all output kinds: exclusion, nullability, transformer,
 * and pass-through annotations. For output-kind-specific params (rename, validators) or to
 * target a subset of outputs, use [FieldOverride] instead.
 *
 * [FieldOverride] params win over [FieldSpec] for the same [property] + suffix combination.
 *
 * **Example**:
 * ```kotlin
 * @FieldSpec(property = "passwordHash", exclude = true)        // excluded from all outputs
 * @FieldSpec(property = "createdAt", nullable = NullableOverride.YES)
 * ```
 *
 * @param property        Name of the domain property to configure.
 * @param exclude         When `true`, omits this field from every generated output class.
 * @param nullable        Nullability override; [NullableOverride.UNSET] preserves the source type.
 * @param transformer     [FieldTransformer] class for value conversion.
 * @param annotations     Annotations forwarded to the generated field in every output class.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
@Repeatable
annotation class FieldSpec(
    val property: String,
    val exclude: Boolean = false,
    val nullable: NullableOverride = NullableOverride.UNSET,
    val transformer: KClass<out FieldTransformer<*, *>> = NoOpTransformer::class,
    val annotations: Array<CustomAnnotation> = []
)
