package com.example.annotations

import kotlin.reflect.KClass

/**
 * Drives generation of a single output class from a domain type.
 *
 * Apply multiple `@ClassSpec` annotations to the same spec class to generate several output
 * classes from one domain type. Each instance is uniquely identified by [suffix], which is
 * also used by [FieldSpec.for_] to scope field overrides to a specific output class.
 *
 * **Output-kind inference** (processor):
 * - Any [FieldSpec] scoped to this suffix has non-empty [FieldSpec.rules] → request class
 *   (generates an `init {}` block with `require()` calls).
 * - [partial] = `true` → all fields are nullable with `= null` defaults (update-request style).
 * - Otherwise → plain data class with bidirectional mapper functions (`to<Suffix>()`/`toDomain()`).
 *
 * **Example**:
 * ```kotlin
 * @ClassSpec(for_ = User::class, suffix = "Entity",
 *            annotations = [CustomAnnotation(Entity::class),
 *                           CustomAnnotation(Table::class, members = ["name=\"users\""])])
 * @ClassSpec(for_ = User::class, suffix = "Response")
 * @ClassSpec(for_ = User::class, suffix = "CreateRequest")
 * @ClassSpec(for_ = User::class, suffix = "UpdateRequest", partial = true)
 * class UserSpec
 * ```
 *
 * @param for_                   Domain class to generate from.
 * @param suffix                 Appended to the domain class name to form the output class name.
 *                               Also used as the discriminator by [FieldSpec.for_].
 * @param prefix                 Prepended to the domain class name.
 * @param partial                When `true`, every generated field is nullable with `= null`.
 * @param bundles                Names of [@FieldBundle] classes whose field configs are merged into this spec.
 * @param bundleMergeStrategy    How to resolve conflicts when spec and bundle configure the same field.
 * @param unmappedNestedStrategy What to do when a nested domain type has no explicit mapping.
 * @param excludedFieldStrategy  How to treat excluded fields in the output class.
 * @param annotations            Annotations forwarded verbatim to the generated class (e.g. `@Entity`).
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
@Repeatable
annotation class ClassSpec(
    val for_: KClass<*>,
    val suffix: String = "",
    val prefix: String = "",
    val partial: Boolean = false,
    val bundles: Array<String> = [],
    val bundleMergeStrategy: BundleMergeStrategy = BundleMergeStrategy.SPEC_WINS,
    val unmappedNestedStrategy: UnmappedNestedStrategy = UnmappedNestedStrategy.FAIL,
    val excludedFieldStrategy: ExcludedFieldStrategy = ExcludedFieldStrategy.USE_DEFAULT,
    val annotations: Array<CustomAnnotation> = []
)

/**
 * Shared field override applied to **every** output class generated by this spec class.
 *
 * Only carries params meaningful for all output kinds: exclusion, nullability, transformer,
 * and pass-through annotations. For output-kind-specific params (column name, rename,
 * validation rules) or to target a subset of outputs, use [FieldSpec] instead.
 *
 * [FieldSpec] params win over [ClassField] for the same [property] + suffix combination.
 *
 * **Example**:
 * ```kotlin
 * @ClassField(property = "passwordHash", exclude = true)        // excluded from all outputs
 * @ClassField(property = "createdAt", nullable = NullableOverride.YES)
 * ```
 *
 * @param property        Name of the domain property to configure.
 * @param exclude         When `true`, omits this field from every generated output class.
 * @param nullable        Nullability override; [NullableOverride.UNSET] preserves the source type.
 * @param transformer     [FieldTransformer] class for value conversion.
 * @param transformerRef  Named transformer from a [TransformerRegistry]; wins over [transformer].
 * @param annotations     Annotations forwarded to the generated field in every output class.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
@Repeatable
annotation class ClassField(
    val property: String,
    val exclude: Boolean = false,
    val nullable: NullableOverride = NullableOverride.UNSET,
    val transformer: KClass<out FieldTransformer<*, *>> = NoOpTransformer::class,
    val transformerRef: String = "",
    val annotations: Array<CustomAnnotation> = []
)

/**
 * Per-output-class field override, scoped to one or more [ClassSpec] instances by [for_].
 *
 * [for_] lists the [ClassSpec.suffix] values this override applies to, allowing the same
 * rule set to be shared across `CreateRequest` and `UpdateRequest` without duplication.
 * [FieldSpec] params win over [ClassField] for the same [property] + suffix combination.
 *
 * **Flat design** — all output-kind-specific params coexist; the processor ignores inapplicable ones:
 * - Entity-specific:  [column], [inline], [inlinePrefix]
 * - DTO-specific:     [rename]
 * - Request-specific: [rules] (each rule class must be annotated with [@RuleExpression])
 *
 * **Example**:
 * ```kotlin
 * @FieldSpec(for_ = ["Entity"],   property = "createdAt", column = "created_at")
 * @FieldSpec(for_ = ["Response"], property = "createdAt", rename = "updatedAt")
 * @FieldSpec(for_ = ["CreateRequest", "UpdateRequest"],
 *            property = "email",
 *            rules   = [Rule.Email::class, Rule.NotBlank::class])
 * ```
 *
 * @param for_           One or more [ClassSpec.suffix] values this override applies to.
 * @param property       Name of the domain property to configure.
 * @param exclude        Omit this field from the named output class(es) only.
 * @param nullable       Nullability override for the named output class(es).
 * @param transformer    [FieldTransformer] class for value conversion.
 * @param transformerRef Named transformer; wins over [transformer].
 * @param annotations    Annotations forwarded to the generated field in the named output class(es).
 * @param column         Database column name (entity output).
 * @param inline         Flatten a nested domain object's fields into this entity (entity output).
 * @param inlinePrefix   Prefix prepended to inlined field names (entity output).
 * @param rename         Alternative field name in the generated class (DTO output).
 * @param rules          Validation rules; each must be annotated with [@RuleExpression] (request output).
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
@Repeatable
annotation class FieldSpec(
    val for_: Array<String>,
    val property: String,
    val exclude: Boolean = false,
    val nullable: NullableOverride = NullableOverride.UNSET,
    val transformer: KClass<out FieldTransformer<*, *>> = NoOpTransformer::class,
    val transformerRef: String = "",
    val annotations: Array<CustomAnnotation> = [],
    // Entity-specific
    val column: String = "",
    val inline: Boolean = false,
    val inlinePrefix: String = "",
    // DTO-specific
    val rename: String = "",
    // Request-specific
    val rules: Array<KClass<out Annotation>> = []
)
